### ISSUE TITLE
Undefined Variable Notice

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/activity_calendar#10]
After disabling the `flag activity` module, I notice that I am still getting the following notices in the log. 

`Notice: Undefined variable: user_activity in activity_calendar_block_contents() (line 288 of /var/www/***/****/***/src/modules/triplo/activity_calendar/activity_calendar.module).`

**Comment by alanmels** [comment]
If the module was indeed disabled then that kind of error message was not supposed to be triggered at all. However, if the module is still called, then I believe it's about one of number of new variables introduced in the last dev branch, so probably the upgrade path needs to be thought. However, as an urgent remedy disabling, uninstalling and making sure the configuration file has been removed, and then only enabling the last dev branch should help.
