### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/activity_calendar#5]
I am getting the following notices in the log (admin/reports/dblog):

`Notice: Undefined variable: user_activity in activity_calendar_user_view_alter() (line 109 of /var/www/<custom path>/src/modules/contrib/activity_calendar/activity_calendar.module).`

AND

`Warning: array_keys() expects parameter 1 to be array, null given in activity_calendar_user_view_alter() (line 88 of /var/www/<custom path>/src/modules/contrib/activity_calendar/activity_calendar.module)`

**Comment by alanmels** [comment]
@stpaultim, From https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Activity.20Calendar.20module/near/224611876 I understand you somehow got the outdated version. Can you please confirm the issue persists even on the latest one?

**Comment by alanmels** [comment]
You're right, @stpaultim, I've just tested on a fresh install and got the error. Will look into it today.

**Comment by stpaultim** [comment]
Yeah, I just checked and I am using 1.x-1.0.3
