### ISSUE TITLE
Track flag activity

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/activity_calendar#6]
I am testing this module on the current survey site we are using to prioritize core development issues. I'm just using the survey site as an opportunity to test the module and allow others in the community to try it. 

https://survey.backdropcms.org/

Unfortunately, it does not track the main activity that we expect from users, which is flagging/voting on issues. 

In fact, I'm not sure if flagging issues would normally be the kind of activity that you would want to track with this module, but it would be nice on this particular site. Although even then, I'm not sure how to track flags. I don't think I would want to give points for every flag/vote cast. Ideally, users would get a single point if they flag any content during the day, but would not get points for each flag. 

Anyway, this is just an idea. I'm not sure it's a common enough use case to worry about.

**Comment by alanmels** [comment]
I thinks it's possible by providing a new hook to other modules, so they control what to feed the activity calendar with. It will take some time, but I'll think how to implement tracking flagging/voting. Thanks for the suggestion!

**Comment by alanmels** [comment]
@stpaultim Flag module support has been added. You need to enable the Flag Activity sub-module. 

However, please note that any flagging will get the preset points for now. It is possible to modify the database query in the flag_activity.module file, so users get single point for any flagging per day, however it has two issues:

1) That kind of setup hardly would fall under the "80% use" principle, so it's better if you just modify the query in a custom module;
2) Imagine the less likely, but still possible scenario: A user logs in and makes all the flagging/voting on one day to get the preset points. Another user, on the contrary, logs in and makes just one flagging/voting on a given day. He then logs in the next day to make another flagging, and so on and so on. And despite both users demonstrated the same or similar number of flagging/voting, the calendar will look different for two users.

So in your use case, I believe, it's better to track just user logins (assuming that if someone made an effort to login to https://survey.backdropcms.org then s/he did that to definitely flag/vote) and not flagging/voting. Do you think tracking logins instead works for your use case better?

**Comment by alanmels** [comment]
Another idea for your use-case: set both minimum and maximum colors to the same color, and then it wouldn't matter who flagged how many times on a certain day. The calendar should look the same color, however with only those days highlighted when a user flagged/voted.

**Comment by alanmels** [comment]
And since the Flag Activity sub-module has already been enabled on https://survey.backdropcms.org I am closing this issue.
