### ISSUE TITLE
Unsupported Operand Types

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/activity_calendar#9]
I just installed the latest version of Activity Tracker on the survey site and got the following error. It's a pretty serious error and is breaking the site. 

Error: Unsupported operand types in activity_calendar_block_contents() (line 274 of /var/www/triplo/nineteen/simplo/src/modules/triplo/activity_calendar/activity_calendar.module).

Will first disable the new flag tracker sub-module and the try reverting to earlier version.

**Comment by stpaultim** [comment]
Disabling the `flag activity` sub-module removed this error.

**Comment by alanmels** [comment]
Scratching my head to think how to replicate the error... I'll run some tests.

**Comment by alanmels** [comment]
Closing this in favor of https://github.com/backdrop-contrib/activity_calendar/issues/10 as this one is related.
